local oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO = {
	_uwUOwOuwuUwUUwUOwOuWUOwOowOOwOUwU = 97,
	_uWUUwUOwOUwUowOOwoUwUOwoOwOuwUOwo = 103,
	_UwuOwoOwOOwOoWOUwUuWuOwOowOUwUuwU = 97,
	_owoUwuowOOWOOwouwUOwoOwOoWoUwUoWo = 109,
	_uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU = 101,
	_uWUuWUUWuUwUOwoOWOuwUUwUOwOuWuoWo = 80,
	_OwoUwUuwUUwUOwOOwOuwuuwUUwuUwUuwU = 108,
	_uWuOwOuwUoWOUwuUwUuwUOwoOwOOwOOwO = 121,
	_uwUuwUowOuwUUwUowoUwuUwUUwUuWuowO = 114,
	_uwUuwUUwUOwOOwoOWoUwUuwUowOUwuuwU = 115,
	_OwOOWOuwUUwuUwuoWoOwoowoUwUOwOowO = 82,
	_oWoowoUwuOwOowOOwoOWOuwUOwoOwoOwo = 117,
	_UWuUwuUwUOwOoWOUWuoWoUwUUWUuwUuwu = 110,
	_uwUOWOOwOowOowOOwOuwUUwUOwOOWoUwu = 83,
	_UwUowooWOOwOuwUOwOUWuUWuOwOuwUuwU = 118,
	_uwUOwOUwuuWuOwOOwouwUUwUOwOowOOwo = 105,
	_UwuUWuUwUUwUUWUOwOOwoUwUuwUOWOUwU = 99,
	_OwouWuuwUuwuOwOUwUUWUUwuUwuuwUUwU = 66,
	_UwUOwOUwUUwuOwoUwUOwOUwUUwUowOuwU = 111,
	_uwUOwoUwuuwUOwoOWOUwUUwUuwUowOOwo = 107,
	_UwUOwOOwOowOOwOuwUUwUOwOoWOUwuowO = 65,
	_OwOOWOUWuowOowOUwuuwUOwOuwUOwOuwU = 116,
	_UwuuwUOwOOwOUwuUwUUwUUwuuwUuWUuwU = 85,
	_OwoUwuoWOuwUOwOuwuuwUowOOwOowOOwO = 104,
	_UwuOwOUwUuwUuwUOwOUwUOwOOwOuwUOwO = 112,
	_UwUowOowOOwOUwuOwOUWUOwOuWuUwuOwO = 72,
	_OwoUwuowOOwOUwUOwOUwUowOuWuuwUUwu = 75,
	_OwOUwuuwUUwUOwoowOUwUOwOuWUuWUOwO = 100,
	_UwUUwUOwOOwouwuOWoUWUOwOoWOOwOowO = 84,
	_uwUowOuwuOwouWUuwUOwoOwOOWoUWUOwO = 76,
	_OwOuwUUwuuwUuwUuwUUwUUwUUwuoWOOwo = 119,
	_UwUUwUuwUUwUuwUOwOUwUuwUOwOOwOUwU = 86,
	_uwUoWOUwuUwUuwUUwUOwoUwUOwouwUowO = 77,
}
local OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu = string
local uwUOWouwUUwUuWUUwuowOUwUuwUoWoOwoUwUOwOuWUOwOOwOOwOOWoowoUwUOwO =
	getfenv()[OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
		(function(
			OwOuwUuwUuwUuwUOwOUwuOwOuwuOWouwUOwOUwUUwUUwUOwoUwUoWoOWouwUUwU,
			OwOowOUwUowOOwOuWUOWoUwuoWOoWOowoowoOwOOwOuwUuWuowOOwOOWOUWUOwO
		)
			local OwOUWuUwUuwUowOUwuuwUOwoOwOUwuOwOUwuOwOOwOUwuOWOuwUOwOUwUUwUOwo = { 785, 696, 201, 254, 274 }
			return #OwOUWuUwUuwUowOUwuuwUOwoOwOUwuOwOUwuOwOOwOUwuOWOuwUOwOUwUUwUOwo
		end)() + 107,
		oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwuUwUUwUOwOuWUOwOowOOwOUwU,
		(function(
			OwOOwOOwOOWoOwouwUuwUOwoOwoUwUUwuOwOOwOOwOOwOOWOuwUuWUOwoOwOowO,
			uwUOwOOwOOwoOwOOwoUWUOwOOwOuwUUWUOwOowoOwOUwUuWuOWOuWuUwUOwoOWo
		)
			local OwoOwoUwUOwOUwuuwUOwOowouwUUWuoWOOwOOwOOWoOwoUWUOwoOwOUwUuWuoWO = { 824, 316, 315, 77, 528 }
			return #OwoOwoUwUOwOUwuuwUOwOowouwUUWuoWOOwOOwOOWoOwoUWUOwoOwOUwUuWuoWO
		end)() + 100,
		(function(
			OwOOwOOwOUwUOwoOwouwuowOuwUOwOUwUUWuoWoUwuUwUOwOUwUowouwUOWoowO,
			OwOOwOoWoOwOOWooWOOwoOwOOwOowOowOUwuuwUOwooWOuwuOwoOwoUwuOwOOWo
		)
			local OwoOwOOwooWOuwUOWOUwUOwoUwuOwOUwUOwOowOuwUuwUUwUOwOOwOOwOOwOUwU = { 38, 816, 247, 174, 883 }
			return #OwoOwOOwooWOuwUOWOUwUOwoUwuOwOUwUOwOowOuwUuwUUwUOwOOwOOwOOwOUwU
		end)() + 109,
		(function()
			local owOUwuowOuWUOwoOwOOwOOwoUWuUwUUwUowoOwOuwUUwUOwOUwUUwuuwUUwUuwU =
				"3E15F1C60CD9ACBE17DACD2EB06E115942EEDA2FC228B6F3D72373238D273EA3050B502F698FE971D9C21B1051C567FAEA68"
			return #owOUwuowOuWUOwoOwOOwOOwoUWuUwUUwUowoOwOuwUUwUOwOUwUUwuuwUUwUuwU + 15
		end)()
	) .. OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char() .. ""]
local UwUUwUuwUuwuUwUOwOUWUowOUwuUwUuwUuWuUwUuwUOwOoWoUwUowouwUUwuOwO =
	getfenv()[OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
		oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uWUUwUOwOUwUowOOwoUwUOwoOwOuwUOwo,
		oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuOwoOwOOwOoWOUwUuWuOwOowOUwUuwU,
		oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._owoUwuowOOWOOwouwUOwoOwOoWoUwUoWo,
		oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU
	) .. ""]
local uwUUwUUwUuwUOwOuWuUWUuwuuWUOwOOwOoWOoWoOwoUwuUwUUwUuwuOwoUwUUwU =
	UwUUwUuwUuwuUwUOwOUWUowOUwuUwUuwUuWuUwUuwUOwOoWoUwUowouwUUwuOwO:GetService(
		OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uWUuWUUWuUwUOwoOWOuwUUwUOwOuWuoWo,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwUuwUUwUOwOOwOuwuuwUUwuUwUuwU,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuOwoOwOOwOoWOUwUuWuOwOowOUwUuwU,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uWuOwOuwUoWOUwuUwUuwUOwoOwOOwOOwO,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUuwUowOuwUUwUowoUwuUwUUwUuWuowO,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUuwUUwUOwOOwoOWoUwUuwUowOUwuuwU
		) .. ""
	).LocalPlayer
local uwuOwoUwuOwOuwUOwOOwOoWOOwOuwUOwOuWUowOOwOOwOUwUOwoowOuWuuwUowO =
	UwUUwUuwUuwuUwUOwOUWUowOUwuUwUuwUuWuUwUuwUOwOoWoUwUowouwUUwuOwO:GetService(
		OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwOOWOuwUUwuUwuoWoOwoowoUwUOwOowO,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._oWoowoUwuOwOowOOwoOWOuwUOwoOwoOwo,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UWuUwuUwUOwOoWOUWuoWoUwUUWUuwUuwu,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOWOOwOowOowOOwOuwUUwUOwOOWoUwu,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUuwUowOuwUUwUowoUwuUwUUwUuWuowO,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUowooWOOwOuwUOwOUWuUWuOwOuwUuwU,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOUwuuWuOwOOwouwUUwUOwOowOOwo,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuUWuUwUUwUUWUOwOOwoUwUuwUOWOUwU,
			oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU
		) .. ""
	)
uwuOwoUwuOwOuwUOwOOwOoWOOwOuwUOwOuWUowOOwOOwOUwUOwoowOuWuuwUowO.RenderStepped:connect(function()
	for
		OwOuWUOwoUwUOwOUwuOwouwUowOOwOowOuwUOwOuwUuwUuwuOwOoWoUwUowOuwu,
		UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO
	in
		uwUOWouwUUwUuWUUwuowOUwUuwUoWoOwoUwUOwOuWUOwOOwOOwOOWoowoUwUOwO(
			uwUUwUUwUuwUOwOuWuUWUuwuuWUOwOOwOoWOoWoOwoUwuUwUUwUuwuOwoUwUUwU.Character:GetChildren()
		)
	do
		if
			UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO.Name
			== OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwouWuuwUuwuOwOUwUUWUUwuUwuuwUUwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwUuwUUwUOwOOwOuwuuwUUwuUwUuwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUOwOUwUUwuOwoUwUOwOUwUUwUowOuwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuUWuUwUUwUUWUOwOOwoUwUuwUOWOUwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwoUwuuwUOwoOWOUwUUwUuwUowOOwo
				)
				.. ""
		then
			UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO.Value = false
		end
		if
			UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO.Name
				== OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUOwOOwOowOOwOuwUUwUOwOoWOUwuowO,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuUWuUwUUwUUWUOwOOwoUwUuwUOWOUwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwOOWOUWuowOowOUwuuwUOwOuwUOwOuwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOUwuuWuOwOOwouwUUwUOwOowOOwo,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUOwOUwUUwuOwoUwUOwOUwUUwUowOuwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UWuUwuUwUOwOoWOUWuoWoUwUUWUuwUuwu
				) .. ""
			or UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO.Name == OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUOwOOwOowOOwOuwUUwUOwOoWOUwuowO,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwOOWOUWuowOowOUwuuwUOwOuwUOwOuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwOOWOUWuowOowOUwuuwUOwOuwUOwOuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuOwoOwOOwOoWOUwUuWuOwOowOUwUuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuUWuUwUUwUUWUOwOOwoUwUuwUOWOUwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwoUwuuwUOwoOWOUwUUwUuwUowOOwo,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOUwuuWuOwOOwouwUUwUOwOowOOwo,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UWuUwuUwUOwOoWOUWuoWoUwUUWUuwUuwu,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uWUUwUOwOUwUowOOwoUwUOwoOwOuwUOwo
			) .. ""
			or UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO.Name == OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuuwUOwOOwOUwuUwUUwUUwuuwUuWUuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUuwUUwUOwOOwoOWoUwUuwUowOUwuuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOUwuuWuOwOOwouwUUwUOwOowOOwo,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UWuUwuUwUOwOoWOUWuoWoUwUUWUuwUuwu,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uWUUwUOwOUwUowOOwoUwUOwoOwOuwUOwo
			) .. ""
			or UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO.Name == OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwuoWOuwUOwOuwuuwUowOOwOowOOwO,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uWuOwOuwUoWOUwuUwUuwUOwoOwOOwOOwO,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuOwOUwUuwUuwUOwOUwUOwOOwOuwUOwO,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUuwUowOuwUUwUowoUwuUwUUwUuWuowO
			) .. ""
			or UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO.Name == OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUowOowOOwOUwuOwOUWUOwOuWuUwuOwO,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uWuOwOuwUoWOUwuUwUuwUOwoOwOOwOOwO,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuOwOUwUuwUuwUOwOUwUOwOOwOuwUOwO,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUuwUowOuwUUwUowoUwuUwUUwUuWuowO
			) .. ""
			or UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO.Name == OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwuoWOuwUOwOuwuuwUowOOwOowOOwO,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuOwoOwOOwOoWOUwUuWuOwOowOUwUuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUowooWOOwOuwUOwOUWuUWuOwOuwUuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uWuOwOuwUoWOUwuUwUuwUOwoOwOOwOOwO
			) .. ""
			or UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO.Name == OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwuowOOwOUwUOwOUwUowOuWuuwUUwu,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOUwuuWuOwOOwouwUUwUOwOowOOwo,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwouWuuwUuwuOwOUwUUWUUwuUwuuwUUwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwUuwUUwUOwOOwOuwuuwUUwuUwUuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuOwoOwOOwOoWOUwUuWuOwOowOUwUuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUuwUUwUOwOOwoOWoUwUuwUowOUwuuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwOOWOUWuowOowOUwuuwUOwOuwUOwOuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwOUwuuwUUwUOwoowOUwUOwOuWUuWUOwO
			) .. ""
			or UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO.Name == OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUUwUOwOOwouwuOWoUWUOwOoWOOwOowO,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwUuwUUwUOwOOwOuwuuwUUwuUwUuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU
			) .. ""
			or UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO.Name == OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwOOWOUWuowOowOUwuuwUOwOuwUOwOuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwUuwUUwUOwOOwOuwuuwUUwuUwUuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU
			) .. ""
			or UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO.Name == OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwuowOOwOUwUOwOUwUowOuWuuwUUwu,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOUwuuWuOwOOwouwUUwUOwOowOOwo,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwUuwUUwUOwOOwOuwuuwUUwuUwUuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwUuwUUwUOwOOwOuwuuwUUwuUwUuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwOUwuuwUUwUOwoowOUwUOwOuWUuWUOwO
			) .. ""
			or UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO.Name == OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUowOuwuOwouWUuwUOwoOwOOWoUWUOwO,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUOwOUwUUwuOwoUwUOwOUwUUwUowOuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUOwOUwUUwuOwoUwUOwOUwUUwUowOuwU,
				oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwoUwuuwUOwoOWOUwUUwUuwUowOOwo
			) .. ""
			or UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO.Name
				== OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOWOOwOowOowOOwOuwUUwUOwOOWoUwu,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwUuwUUwUOwOOwOuwuuwUUwuUwUuwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUOwOUwUUwuOwoUwUOwOUwUUwUowOuwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwOuwUUwuuwUuwUuwUUwUUwUUwuoWOOwo
				) .. ""
		then
			UwUOwouwUUwUuWuUWuuwUOwOUwUOWoowOUwUOWOuwUUwUUwUoWOOwouwUUwUOWO:Destroy()
		end
	end
	for
		OWOUwUOwOowoOwOoWouwUoWOOwOUwUOwoOwOUwUuwUUwuOwOuWUowOuwUOwOOWo,
		owOOwOUwUUwUuwUUWUOWoUwuuwUowOUwUuwUOwoUwuUwUOwoOwoUWuuwUowoUwU
	in
		uwUOWouwUUwUuWUUwuowOUwUuwUoWoOwoUwUOwOuWUOwOOwOOwOOWoowoUwUOwO(
			uwUUwUUwUuwUOwOuWuUWUuwuuWUOwOOwOoWOoWoOwoUwuUwUUwUuwuOwoUwUUwU.Character.HumanoidRootPart:GetChildren()
		)
	do
		if
			owOOwOUwUUwUuwUUWUOWoUwuuwUowOUwUuwUOwoUwuUwUOwoOwoUWuuwUowoUwU.Name
			== OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwouWuuwUuwuOwOUwUUWUUwuUwuuwUUwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUOwOUwUUwuOwoUwUOwOUwUUwUowOuwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwOUwuuwUUwUOwoowOUwUOwOuWUuWUOwO,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uWuOwOuwUoWOUwuUwUuwUOwoOwOOwOOwO,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUUwUuwUUwUuwUOwOUwUuwUOwOOwOUwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwUuwUUwUOwOOwOuwuuwUUwuUwUuwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUOwOUwUUwuOwoUwUOwOUwUUwUowOuwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuUWuUwUUwUUWUOwOOwoUwUuwUOWOUwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOUwuuWuOwOOwouwUUwUOwOowOOwo,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwOOWOUWuowOowOUwuuwUOwOuwUOwOuwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uWuOwOuwUoWOUwuUwUuwUOwoOwOOwOOwO
				)
				.. ""
		then
			owOOwOUwUUwUuwUUWUOWoUwuuwUowOUwUuwUOwoUwuUwUOwoOwoUWuuwUowoUwU:Destroy()
		end
	end
	for
		UwuowOUwUUwUUwUUwUUWUUwUowOuWUUwUowOUwUUwUowOUwuOwOUwuOwOOwOOwO,
		owoOwOOwOUwUOwOUwUoWoOwOOwOOwOUwuUWUOwOUWuOwOOwOowOOwoUwUOwOOwO
	in
		uwUOWouwUUwUuWUUwuowOUwUuwUoWoOwoUwUOwOuWUOwOOwOOwOOWoowoUwUOwO(
			uwUUwUUwUuwUOwOuWuUWUuwuuWUOwOOwOoWOoWoOwoUwuUwUUwUuwuOwoUwUUwU.Character:GetChildren()
		)
	do
		if
			owoOwOOwOUwUOwOUwUoWoOwOOwOOwOUwuUWUOwOUWuOwOOwOowOOwoUwUOwOOwO.ClassName
			== OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUoWOUwuUwUuwUUwUOwoUwUOwouwUowO,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUuwUUwUOwOOwoOWoUwUuwUowOUwuuwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwuoWOuwUOwOuwuuwUowOOwOowOOwO,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uWUuWUUWuUwUOwoOWOuwUUwUOwOuWuoWo,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuOwoOwOOwOoWOUwUuWuOwOowOUwUuwU,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUuwUowOuwUUwUowoUwuUwUUwUuWuowO,
					oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwOOWOUWuowOowOUwuuwUOwOuwUOwOuwU
				)
				.. ""
		then
			for
				owOOwOUwUOwOowOUwUUwUOwOOwOuwUuwuuwUUwUUwuUwUOwOUwUuwUUwuowouwU,
				owOUwUuwUowOowOOwOuwUuwUUwUowoOwoUwUOwOUwuowOOwOOwOowOowOuWUuWu
			in
				uwUOWouwUUwUuWUUwuowOUwUuwUoWoOwoUwUOwOuWUOwOOwOOwOOWoowoUwUOwO(
					owoOwOOwOUwUOwOUwUoWoOwOOwOOwOUwuUWUOwOUWuOwOOwOowOOwoUwUOwOOwO:GetChildren()
				)
			do
				if
					owOUwUuwUowOowOOwOuwUuwUUwUowoOwoUwUOwOUwuowOOwOOwOowOowOuWUuWu.Name
					== OwoOWoOwouwUOwOUwUuwUOwOUwUowOowOOwOOWOUwUUwUuwUOwOOwOUwUUwUUwu.char(
							oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwouWuuwUuwuOwOUwUUWUUwuUwuuwUUwU,
							oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUOwOUwUUwuOwoUwUOwOUwUUwUowOuwU,
							oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwOUwuuwUUwUOwoowOUwUOwOuWUuWUOwO,
							oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uWuOwOuwUoWOUwuUwUuwUOwoOwOOwOOwO,
							oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUUwUuwUUwUuwUOwOUwUuwUOwOOwOUwU,
							oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOuwUOwoOwOUwuuwUUwUuwUowOuwU,
							oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwoUwUuwUUwUOwOOwOuwuuwUUwuUwUuwU,
							oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwUOwOUwUUwuOwoUwUOwOUwUUwUowOuwU,
							oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._UwuUWuUwUUwUUWUOwOOwoUwUuwUOWOUwU,
							oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uwUOwOUwuuWuOwOOwouwUUwUOwOowOOwo,
							oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._OwOOWOUWuowOowOUwuuwUOwOuwUOwOuwU,
							oWOuwuOwoUwUUwUOwouwUowOUwuUwUOWOuwUOWOUWuuwUoWOowOuWUOwOuWuOwO._uWuOwOuwUoWOUwuUwUuwUOwoOwOOwOOwO
						)
						.. ""
				then
					owOUwUuwUowOowOOwOuwUuwUUwUowoOwoUwUOwOUwuowOOwOOwOowOowOuWUuWu:Destroy()
				end
			end
		end
	end
end)
